apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/asaran-tenant/partner-catalog/partner-catalog@sha256:2c722cadbd81f11b78ca4dac08ec1d2fd20910b378a18703d85e7a794aaa074f
        name: my-java-springboot
        resources: {}
status: {}
